version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
      - run: ./cibuild.sh fedora:31
      - run: ./cibuild.sh fedora:31 openjdk8
      - run: ./cibuild.sh fedora:31 openjdk8 gradle:4
      - run: ./cibuild.sh fedora:31 openjdk8 gradle:4 node:10
      - run: ./cibuild.sh fedora:31 node:10
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
