version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run: pip3 install --user docker
      - run: docker ps
      - run: ./build.py -n b1zzu fedora:31
      - run: ./build.py -n b1zzu fedora:31 openjdk8
      - run: ./build.py -n b1zzu fedora:31 openjdk8 gradle:5.6
      - run: ./build.py -n b1zzu fedora:31 openjdk8 gradle:5.6 node:10.16.2
      - run: ./build.py -n b1zzu node:10.16.2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build