version: 2
jobs:
  build:
    docker:
      - image: b1zzu/python:alpha-fedora31-docker18-python3
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
      - run: pip3 install PyYAML
      - run: ./cibuild.sh _all_
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
